version: "3"
services:
  httpd:
    environment:
      - SHIBD_HOSTNAME=shibd
    depends_on:
      - shibd
    build:
      context: .
      dockerfile: Dockerfile.httpd
    image: techservicesillinois/httpd
    ports:
      - "80:8080"
    networks:
      - frontend
      - backend
  shibd:
    build:
      context: .
      dockerfile: Dockerfile.shibd
    image: techservicesillinois/shibd
    environment:
      - HTTPD_HOSTNAME=httpd
    depends_on:
      - cron
    ports:
      - "1600:1600"
    networks:
      - backend
    volumes:
      - keys:/var/shib-keys:ro
      - ~/.aws:/var/run/shibboleth/.aws:ro
  cron:
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: techservicesillinois/shib-data-sealer
    volumes:
      - keys:/var/shib-keys
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
networks:
  frontend:
  backend:

volumes:
  keys:
