FROM techservicesillinois/shibd-base

COPY shibboleth2.xml.shibd /var/run/shibboleth/shibboleth2.xml
COPY entrypoint-shibd.sh get-shib-keys/get-shib-keys /usr/local/bin/
 
VOLUME ["/var/shib-keys"]

ENV LD_LIBRARY_PATH /opt/shibboleth/lib64

USER shibd
EXPOSE 1600

ENTRYPOINT [ "/usr/local/bin/entrypoint-shibd.sh" ]
