version: "3"
services:
  alb:
    image: nginx:1.14
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    networks:
      - frontend
  httpd:
    environment:
      LB_HOSTNAME: alb
      SHIBD_HOSTNAME: shibd
      ELMR_HOSTNAME: elmr
      NO_SHIBD: "True"
      displayName: John Doe
      eppn: jkdoe@illinois.edu
    depends_on:
      - shibd
      - elmr
    build:
      context: .
      dockerfile: Dockerfile.httpd
    image: techservicesillinois/httpd
    networks:
      - frontend
      - backend
  shibd:
    build:
      context: .
      dockerfile: Dockerfile.shibd
    image: techservicesillinois/shibd
    environment:
      - HTTPD_HOSTNAME=httpd
    depends_on:
      - cron
    networks:
      - backend
    volumes:
      - keys:/var/shib-keys:ro
      - ~/.aws:/var/run/shibboleth/.aws:ro
  cron:
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: techservicesillinois/shib-data-sealer
    volumes:
      - keys:/var/shib-keys
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
  elmr:
    image: techservicesillinois/elmr
    environment:
      REDIS_HOSTNAME: redis
    networks:
      - backend
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
  service:
    image: techservicesillinois/elmrsample
    environment:
      REDIS_HOSTNAME: redis
    ports: 
      - "8081:8081"
    networks:
      - frontend
networks:
  frontend:
  backend:

volumes:
  keys:
