version: "3"
services:
  httpd:
    environment:
      - SHIBD_HOSTNAME=shibd
    depends_on: 
      - shibd
    build: .
    image: illinois-httpd-img
    ports:
      - "80:8080"
    networks:
      - webnet
  shibd:
    build:
      context: .
      dockerfile: Dockerfile.shibd
    image: illinois-shibd-sp-img
    command: /usr/sbin/shibd -F -f 
    ports:
      - "1600:1600"
    networks:
      - webnet
networks:
  webnet: