version: "3"
services:
  httpd:
    environment:
      SHIBD_HOSTNAME: shibd
      ELMR_HOSTNAME: elmr
      displayName: John Doe
      eppn: jkdoe@illinois.edu
    depends_on:
      - shibd
      - elmr
    build:
      context: .
      dockerfile: Dockerfile.httpd
    image: techservicesillinois/httpd
    ports:
      - "80:8080"
    networks:
      - frontend
      - backend
  shibd:
    build:
      context: .
      dockerfile: Dockerfile.shibd
    image: techservicesillinois/shibd
    environment:
      - HTTPD_HOSTNAME=httpd
    depends_on:
      - cron
    networks:
      - backend
    volumes:
      - keys:/var/shib-keys:ro
      - ~/.aws:/var/run/shibboleth/.aws:ro
  cron:
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: techservicesillinois/shib-data-sealer
    volumes:
      - keys:/var/shib-keys
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
  elmr:
    image: techservicesillinois/elmr
    networks:
      - backend
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  frontend:
  backend:

volumes:
  keys:
