version: "3"
services:
  httpd:
    environment:
      - SHIBD_HOSTNAME=shibd
      - SHIBD_ACL=0.0.0.0
      - APP_SERVER_NAME=127.0.0.1
      - SHIBD_IDP=urn:mace:incommon:uiuc.edu
    depends_on:
      - shibd
    build:
      context: .
      dockerfile: Dockerfile.httpd
    image: httpd
    ports:
      - "80:8080"
    networks:
      - frontend
      - backend
  shibd:
    build:
      context: .
      dockerfile: Dockerfile.shibd
    image: shibd
    depends_on:
      - cron
    ports:
      - "1600:1600"
    networks:
      - backend
    volumes:
      - keys:/var/shib-keys:ro
  cron:
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    volumes:
      - keys:/var/shib-keys
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
networks:
  frontend:
  backend:

volumes:
  keys:
