version: "2"
services:
  alb:
    image: nginx:1.14
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    networks:
      - frontend
  httpd:
    environment:
      NO_SHIBD: "True"
      displayName: John Doe
      eppn: jkdoe@illinois.edu
    depends_on:
      - config
      - elmr
    volumes_from:
      - config:ro
    build:
      context: httpd
    image: techservicesillinois/httpd
    networks:
      - frontend
      - backend
  shibd:
    build:
      context: shibd
    image: techservicesillinois/shibd
    depends_on:
      - config
      - cron
    networks:
      - backend
    volumes_from:
      - config:ro
      - cron:ro
  config:
    build:
      context: shibd
    image: techservicesillinois/shibd-config
    environment:
      HTTPD_HOSTNAME: httpd
      SHIBD_HOSTNAME: shibd
      ELMR_HOSTNAME: elmr
      LB_HOSTNAME: alb
      REGION: us-east-2
    networks:
      - backend
    volumes:
      - ~/.aws:/root/.aws:ro
  cron:
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
      - LOG_LEVEL=INFO
    build:
      context: cron
    image: techservicesillinois/shib-data-sealer
    volumes:
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
  elmr:
    image: techservicesillinois/elmr
    ports:
      - "8009:8009"
    environment:
      REDIS_HOSTNAME: redis
      DISABLE_SECURE_COOKIES: 'true'
    networks:
      - backend
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
  service:
    image: techservicesillinois/elmrsample
    environment:
      REDIS_HOSTNAME: redis
    ports: 
      - "8081:8081"
    networks:
      - frontend
networks:
  frontend:
  backend:
