FROM shib_base

USER shibd
EXPOSE 1600

COPY shibboleth2.xml.shibd /etc/shibboleth/shibboleth2.xml
COPY entrypoint-shibd.sh /usr/local/bin
 
VOLUME ["/var/shib-keys"]

ENV LD_LIBRARY_PATH /opt/shibboleth/lib64

ENTRYPOINT [ "/usr/local/bin/entrypoint-shibd.sh" ]
