version: "2"
services:
  alb:
    read_only: true
    image: nginx:1.14-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    networks:
      - frontend
    tmpfs:
      - /var/run/nginx
      - /var/cache/nginx
  httpd:
    read_only: true
    environment:
      ELMR_HOSTNAME: elmr
      LB_HOSTNAME: alb
      ENABLE_ELMR_CONFIG: "True"
      ENABLE_ENVIRONMENT_PAGE: "True"
      NO_SHIBD: "True"
      displayName: John Doe
      eppn: jkdoe@illinois.edu
      Shib-Session-ID: 1234
    ports:
      - "8080:8080"
    depends_on:
      - config
    tmpfs:
      - /tmp
    volumes_from:
      - config:ro
    image: $ORG/httpd:$SHIB_IN_A_BOX_TAG
    networks:
      - frontend
      - backend
  shibd:
    read_only: true
    image: $ORG/shibd:$SHIB_IN_A_BOX_TAG
    depends_on:
      - config
      - cron
    networks:
      - backend
    volumes_from:
      - config:ro
      - cron:ro
  config:
    image: $ORG/shibd-config:$SHIB_IN_A_BOX_TAG
    environment:
      HTTPD_HOSTNAME: httpd
      SHIBD_HOSTNAME: shibd
      REGION: us-east-2
      SHIBD_LOG_LEVEL: INFO
      MOD_SHIB_LOG_LEVEL: INFO
      ENTITY_ID: https://multi-service.as-test.techservices.illinois.edu/shibboleth
      SUPPORT_CONTACT: root@localhost
    networks:
      - backend
    volumes:
      - ~/.aws:/var/run/shibboleth/.aws:ro
  cron:
    read_only: true
    environment:
      - SECRET_ID=shib-test5
      - SCHEDULE=* * * * *
      - LOG_LEVEL=INFO
    image: $ORG/shibd-cron:$SHIB_IN_A_BOX_TAG
    volumes:
      - ~/.aws:/var/run/shibboleth/.aws:ro
    networks:
      - frontend
  elmr:
    read_only: true
    environment:
      REDIS_HOSTNAME: redis
      DISABLE_SECURE_COOKIES: 'true'
    image: $ORG/elmr:${ELMR_TAG}
    ports:
      - "8009:8009"
    networks:
      - backend
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend
  service:
    read_only: true
    image: $ORG/elmrsample:${ELMRSAMPLE_TAG}
    environment:
      REDIS_HOSTNAME: redis
    ports: 
      - "8081:8081"
    networks:
      - frontend
    tmpfs:
      - /tmp
networks:
  frontend:
  backend:
