FROM shib_base

RUN yum -y install \
     httpd \
     && yum clean all \
     && rm -rf /var/cache/yum 

COPY entrypoint-httpd.sh /usr/local/bin/
COPY shibboleth2.xml.httpd /etc/shibboleth/shibboleth2.xml
COPY httpd/ /etc/httpd/conf/
COPY environment /var/www/cgi-bin/

RUN chmod 755 /var/www/cgi-bin/environment

EXPOSE 8080 

ENTRYPOINT ["entrypoint-httpd.sh"]
